name: PlatformIO CI

on: [push]

jobs:
  dependencies:
    name: setup dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          platformio update
      - name: Cache PlatformIO
        uses: actions/cache@v3.0.3
        id: platformio-cache
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/lockfiles') }}
      - name: Cache pip
        uses: actions/cache@v3.0.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-py-pip-

  build:
    needs: dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Cache PlatformIO
        uses: actions/cache@v3.0.3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/lockfiles') }}
      - name: list file
        run: ls /home/runner/work/_temp/ -la
      - name: build project
        run: pio run

  lint:
    needs: dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Cache PlatformIO
        uses: actions/cache@v3.0.3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/lockfiles') }}
      - name: list file
        run: ls /home/runner/work/_temp/ -la
      - name: check format
        run: pio check --fail-on-defect high
