name: Build and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
    except:
      - main

jobs:
  setup_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Create virtual environment
        run: |
          python -m venv $HOME/.platformio/venv
          source $HOME/.platformio/venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install platformio
      - name: Cache virtual environment
        uses: actions/cache@v2
        with:
          path: $HOME/.platformio/venv
          key: ${{ runner.os }}-pio
          restore-keys: |
            ${{ runner.os }}-pio
  build:
    needs: setup_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Restore virtual environment cache
        uses: actions/cache@v2
        with:
          path: $HOME/.platformio/venv
          key: ${{ runner.os }}-pio
      - name: Activate virtual environment
        run: source $HOME/.platformio/venv/bin/activate
      - name: Run build
        run: pio run
  static_analysis:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Restore virtual environment cache
        uses: actions/cache@v2
        with:
          path: $HOME/.platformio/venv
          key: ${{ runner.os }}-pio
      - name: Activate virtual environment
        run: source $HOME/.platformio/venv/bin/activate
      - name: Run static analysis
        run: pio check --fail-on-defect high
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Restore virtual environment cache
        uses: actions/cache@v2
        with:
          path: $HOME/.platformio/venv
          key: ${{ runner.os }}-pio
      - name: Activate virtual environment
        run: source $HOME/.platformio/venv/bin/activate
      - name: Run unit tests
        run: pio test
