name: PlatformIO CI

on: [push]

jobs:
  dependencies:
    name: setup dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

  build:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: build project
        run: pio run

  lint:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: check format
        run: pio check --fail-on-defect high
