name: Build and Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Cache platformio
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio
          restore-keys: |
            ${{ runner.os }}-pio
  build:
    needs: setup_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Restore platformio cache
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio
      - name: Run build
        run: pio run
  static_analysis:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Restore platformio cache
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio
      - name: Run static analysis
        run: pio check --fail-on-defect high
  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Restore platformio cache
  #     uses: actions/cache@v2
  #     with:
  #       path: ~/.platformio
  #       key: ${{ runner.os }}-pio
  #   - name: Run unit tests
  #     run: pio test
