name: PlatformIO CI

on: [push]

jobs:
  build_and_check:
    name: setup dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v3.0.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v3.0.3
        id: pio-cache
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          platformio update
      - name: Run build
        run: platformio run
      - name: Run check format
        run: platformio check --fail-on-defect high
