name: PlatformIO CI

on: [push]

jobs:
  dependencies:
    name: setup dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v3.0.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v3.0.3
        id: pio-cache
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-pio-
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

  build:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check path
        run: ls -a
      - name: Cache PlatformIO
        uses: actions/cache@v3.0.3
        id: pio-cache
        with:
          path: ~/.platformio
          restore-keys: |
            ${{ runner.os }}-pio-
      - name: build project
        run: platformio run

  lint:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check path
        run: ls -a
      - name: Cache PlatformIO
        uses: actions/cache@v3.0.3
        id: pio-cache
        with:
          path: ~/.platformio
          restore-keys: |
            ${{ runner.os }}-pio-
      - name: check format
        run: platformio check --fail-on-defect high
