name: Build and Lint

on:
  push:
    branches:
      - main
  pull_request:
    igbranches-ignore:
      - main

jobs:
  setup_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install and cache pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Run install
        run: |
          python -m pip install -r requirements.txt

  build:
    needs: setup_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies from cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Build project
        run: |
          python -m pip install -r requirements.txt
          pio run
  # static_analysis:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Restore virtual environment cache
  #       uses: actions/cache@v2
  #       with:
  #         path: $HOME/.virtualenvs/platformio
  #         key: ${{ runner.os }}-pio
  #     - name: Activate virtual environment
  #       run: source $HOME/.virtualenvs/platformio/bin/activate
  #     - name: Run static analysis
  #       run: pio check --fail-on-defect high
  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Restore virtual environment cache
  #       uses: actions/cache@v2
  #       with:
  #         path: $HOME/.virtualenvs/platformio
  #         key: ${{ runner.os }}-pio
  #     - name: Activate virtual environment
  #       run: source $HOME/.virtualenvs/platformio/bin/activate
  #     - name: Run tests
  #       run: pio test
