name: PlatformIO CI

on: [push]

jobs:
  dependencies:
    name: setup dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        if: steps.cache-pip.outputs.cache-hit != 'true'
        uses: actions/setup-python@v2
      - name: Install pip
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: python -m pip install --upgrade pip
      - run: pip list -v
      - name: Install platformio
        run: |
          pip install -U platformio
          platformio update
      - run: pip list -v
      - name: Cache platformio
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/lockfiles') }}

  build:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache platformio
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/lockfiles') }}
      - name: Cache pip
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip list -v
      - run: |
          pip install -U platformio
          platformio update
      - name: build project
        run: platformio run

  lint:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache platformio
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/lockfiles') }}
      - name: Cache pip
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip list -v
      - run: |
          pip install -U platformio
          platformio update
      - name: check format
        run: platformio check --fail-on-defect high
