name: PRD Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  FIREBASE_CREDENTIAL: ${{ secrets.FIREBASE_CREDENTIAL }}

jobs:
  build:
    name: "Build firmware binary and deploy to could storage"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install required packages
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pip install firebase-admin
          pip install firebase
          pip install python-dotenv
      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Run PlatformIO
        run: pio run
      - name: deploy firmware binary to firebase could storage
        run: |
          FIREBASE_CREDENTIAL=${{env.FIREBASE_CREDENTIAL}} python scripts/deploy.py ${{ steps.get_version.outputs.version }}
